site_name: 学习笔记

nav:
  - 首页: index.md
  - 编程语言:
      - Rust:
         - 概述: programming/rust/index.md
         - clap 命令行解析: programming/rust/clap.md
         - build.rs 构建脚本: programming/rust/build_rs.md
      - TypeScript:
         - 概述: programming/typescript/index.md
      - 垃圾回收算法: programming/garbage-collection-algorithms.md
  - 前端:
      - React: 
         - React: frontend/react/react.md
         - React自定义Hook: frontend/react/react_hook.md
         - React-Router: frontend/react/react-router.md
         - Redux: frontend/react/redux.md
         - Zustand: frontend/react/zustand.md
         - Nextjs: frontend/react/nextjs.md
         - React-Native: frontend/react/react-native.md
         - Shadcn: frontend/react/shadcn.md
         - Antd: frontend/react/antd.md
      - Sass: frontend/sass.md
      - CSS Modules: frontend/css-modules.md
      - Tailwindcss: frontend/tailwindcss.md
      - JavaScript ES6~ES2025: frontend/JavaScript-ES6-to-ES2025.md
      - 现代 Web 平台新特性: frontend/Web-Modern-Features.md
  - 后端:
      - Rust:
         - Axum: backend/rust/axum.md
         - sqlx: backend/rust/sqlx.md
         - Tokio: backend/rust/tokio.md
         - Tonic: backend/rust/tonic.md
         - tracing: backend/rust/tracing.md
      - Redis: backend/redis.md
      - Docker: backend/docker.md
      - SQL: backend/sql.md
      - Nginx: backend/nginx.md
      - MQ: backend/mq.md
      - Protobuf: backend/protobuf.md
      - 微服务: "backend/微服务.md"

  - Flutter:
      - Flutter Agent Skills: flutter/agent-skills.md
      - Flutter Rust Bridge: flutter/flutter-rust-bridge.md
  - Android:
      - Compose: android/compose.md
  - iOS:
      - iOS for Flutter: ios/ios-for-flutter.md
  - CI/CD:
      - Github Actions: cicd/github-actions.md
      - Gitlab CI/CD: cicd/gitlab-cicd.md
      - Jenkins: cicd/jenkins.md
      - Fastlane: cicd/fastlane.md

  - 逆向工程:
      - Frida: reverse_engineering/frida.md
      - Lsposed: reverse_engineering/lsposed.md
      - Jadx: reverse_engineering/jadx.md
      - 主流网络代理与隧道协议详解: reverse_engineering/agent.md
  - 游戏开发:
      - Godot:
          - Godot 引擎入门: game/godot/godot_tutorial.md
          - GDScript: game/godot/gdscript.md
          - Input 输入系统: game/godot/godot-input.md
          - Physics & Signals: game/godot/godot-physics-signals.md
          - Parallax2D: game/godot/godot-Parallax2D.md
          - 常用 2D 节点: game/godot/godot_2d_nodes.md
          - Animation 动画系统: game/godot/godot_animation.md
          - Layout UI 布局: game/godot/godot_layout.md
          - TileMapLayer 瓦片地图: game/godot/godot_tilemaplayer.md

  - AI:
      - GitNexus: ai/GitNexus.md

theme: material
